name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
      fail-fast: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: List files in repository
      run: ls -R

    - name: Build
      run: go build -v ./main.go

    - name: List files in output directory
      run: ls -R output/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: ${{ !github.head_ref }}
      with:
        name: ${{ matrix.goos }}_${{ matrix.goarch }}
        path: output/
